#!/usr/bin/env node
/* ==========================================================================
   train-kitchen.cjs — two cooks, trained separately, then introduced.

   This exists to produce a finding, not just a model. Self-play teaches a pair
   to work together beautifully, and it does that by inventing a convention —
   who fetches, who plates, which way round the kitchen everyone walks. Two
   runs invent different conventions. Put one cook from each together and the
   whole thing falls over, which is a real and well-known result about
   cooperative agents, and the reason "train it by self-play" is not the end of
   the story for anything that has to work with a person.

     node tools/train-kitchen.cjs [--minutes 8] [--seeds 1,2]
   ========================================================================== */

const fs = require('fs');
const path = require('path');
const { KitchenTrainer } = require('../assets/js/lessons/kitchen-train.js');
const { KITCHEN } = require('../assets/js/lessons/kitchen-env.js');

const arg = (name, dflt) => {
  const i = process.argv.indexOf('--' + name);
  return i > 0 && process.argv[i + 1] ? process.argv[i + 1] : dflt;
};

const minutes = parseFloat(arg('minutes', 8));
const seeds = arg('seeds', '1,2,3,4,5,6').split(',').map((s) => parseInt(s, 10));
const KEEP = parseInt(arg('keep', 2), 10);
const EVAL_RUNS = 12;

/* Seed variance on this task is brutal: with identical settings one run reaches
   the scripted pair's score and another never leaves the floor. So train
   several and keep the best, which is ordinary practice and worth being open
   about rather than quietly reporting the good one. */
const round = (w) => Math.round(w * 1e4) / 1e4;

console.log(`Kitchen self-play · seeds ${seeds.join(', ')} · ${minutes} minutes each`);

const trained = [];
const budget = (minutes * 60000) / seeds.length;
for (const seed of seeds) {
  const t = new KitchenTrainer({ seed });
  const start = Date.now();
  while (Date.now() - start < budget) t.trainBatch();
  const score = t.evaluate(t.policy, t.policy, 8).served;
  trained.push({ seed, trainer: t, score });
  console.log(`  seed ${seed}: ${t.episodes} episodes, self-paired ${score.toFixed(2)} soups`);
}

trained.sort((a, b) => b.score - a.score);
const agents = trained.slice(0, KEEP).map((a) => ({ ...a, json: a.trainer.toJSON() }));
console.log(`\nkeeping the best ${KEEP}: seeds ${agents.map((a) => a.seed).join(', ')} ` +
            `(scores ${agents.map((a) => a.score.toFixed(2)).join(', ')})`);
console.log(`discarded: ${trained.slice(KEEP).map((a) => `${a.seed}@${a.score.toFixed(2)}`).join(', ')}`);

/* ---- the measurement the lesson is built on ---- */
const ref = agents[0].trainer;
const scripted = (k, i, rand) => KITCHEN.scriptedCook(k, i, rand);
const results = {};

function score(a, b) { return ref.evaluate(a, b, EVAL_RUNS).served; }

console.log('\nPairings, average soups per 200-tick shift:');
for (const a of agents) {
  results[`self_${a.seed}`] = score(a.trainer.policy, a.trainer.policy);
  console.log(`  seed ${a.seed} with itself          ${results['self_' + a.seed].toFixed(2)}`);
}
if (agents.length > 1) {
  results.cross = score(agents[0].trainer.policy, agents[1].trainer.policy);
  console.log(`  seed ${agents[0].seed} with seed ${agents[1].seed}         ${results.cross.toFixed(2)}`);
}
for (const a of agents) {
  results[`scripted_${a.seed}`] = score(a.trainer.policy, scripted);
  console.log(`  seed ${a.seed} with a by-the-book cook ${results['scripted_' + a.seed].toFixed(2)}`);
}
results.scripted_pair = score(scripted, scripted);
console.log(`  two by-the-book cooks       ${results.scripted_pair.toFixed(2)}`);

const out = {
  version: 1,
  trainedAt: new Date().toISOString().slice(0, 10),
  hp: ref.hp,
  evalRuns: EVAL_RUNS,
  ticks: ref.hp.ticks,
  pairings: results,
  agents: agents.map((a) => ({
    seed: a.seed,
    episodes: a.trainer.episodes,
    net: {
      sizes: a.json.net.sizes,
      acts: a.json.net.acts,
      layers: a.json.net.layers.map((l) => ({ W: l.W.map(round), b: l.b.map(round) })),
    },
  })),
};

const file = path.join(__dirname, '..', 'assets', 'models', 'kitchen-agents.js');
fs.writeFileSync(file,
  '/* Generated by tools/train-kitchen.cjs — self-play kitchen cooks. */\n' +
  'window.ML_KITCHEN = ' + JSON.stringify(out) + ';\n' +
  'if (typeof module === "object" && module.exports) module.exports = window.ML_KITCHEN;\n');
console.log(`\nwrote ${file} (${(fs.statSync(file).size / 1024).toFixed(0)} KB)`);
