/* ==========================================================================
   tools/train-vision.cjs — trains the CNN and the Vision Transformer in a
   headless browser and saves their weights for the site to ship.

       node tools/train-vision.cjs [seconds]

   Why a browser? The digit dataset is generated with the canvas text API, so
   training happens where the data lives. The script drives the real lesson
   pages, waits, and exports the network the page just trained.
   ========================================================================== */

const fs = require('fs');
const path = require('path');

let chromium;
try {
  ({ chromium } = require('playwright'));
} catch (err) {
  console.error('This tool needs Playwright:\n  npm i -D playwright && npx playwright install chromium');
  process.exit(2);
}

const SECONDS = +(process.argv[2] || 90);
const ROOT = path.join(__dirname, '..');
const url = (p) => 'file://' + path.join(ROOT, p);
const round = (a, dp = 4) => a.map((v) => +v.toFixed(dp));

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  page.on('pageerror', (e) => console.error('page error:', e.message));

  /* ---------------------------------------------------------- the CNN */
  console.log(`training the CNN for ${SECONDS}s…`);
  await page.goto(url('lessons/cnn-digits.html'));
  await page.waitForTimeout(2000);
  await page.click('#btn-reset');            // always start from random weights
  await page.click('#btn-train');
  await page.waitForTimeout(SECONDS * 1000);
  await page.click('#btn-train');
  const cnn = await page.evaluate(() => ({
    arch: window.__cnn.arch,
    model: window.__cnn.toJSON(),
    stats: [...document.querySelectorAll('#cnn-stats .stat')]
      .map((e) => e.querySelector('.k').textContent + '=' + e.querySelector('.v').textContent),
    seen: +document.querySelector('#cnn-stats .stat:nth-child(2) .v').textContent.replace(/,/g, ''),
  }));
  cnn.model.params = cnn.model.params.map((layer) => layer.map((p) => round(p)));
  fs.writeFileSync(path.join(ROOT, 'assets/models/cnn-digits.js'),
    '/* Generated by tools/train-vision.cjs — a CNN trained on generated digits. */\n' +
    'window.ML_CNN_MODEL = ' + JSON.stringify(cnn) + ';\n');
  console.log('  ' + cnn.stats.join('  '));

  /* ---------------------------------------------------------- the ViT */
  console.log(`training the Vision Transformer for ${SECONDS * 2}s…`);
  await page.goto(url('lessons/vision-transformer.html'));
  await page.waitForTimeout(2000);
  await page.click('#btn-reset');
  await page.click('#btn-train');
  await page.waitForTimeout(SECONDS * 2000);
  await page.click('#btn-train');
  const vit = await page.evaluate(() => ({
    arch: window.__vit.arch,
    model: window.__vit.toJSON(),
    stats: [...document.querySelectorAll('#vit-stats .stat')]
      .map((e) => e.querySelector('.k').textContent + '=' + e.querySelector('.v').textContent),
    seen: +document.querySelector('#vit-stats .stat:nth-child(2) .v').textContent.replace(/,/g, ''),
  }));
  vit.model.params = vit.model.params.map((p) => round(p));
  fs.writeFileSync(path.join(ROOT, 'assets/models/vit-digits.js'),
    '/* Generated by tools/train-vision.cjs — a small ViT trained on generated digits. */\n' +
    'window.ML_VIT_MODEL = ' + JSON.stringify(vit) + ';\n');
  console.log('  ' + vit.stats.join('  '));

  await browser.close();
  for (const f of ['assets/models/cnn-digits.js', 'assets/models/vit-digits.js']) {
    console.log(`wrote ${f} (${(fs.statSync(path.join(ROOT, f)).size / 1024).toFixed(0)} KB)`);
  }
})();
