#!/usr/bin/env node
/* Trains the two draft models, measures both honestly, and writes the pair the
   lesson page ships. The linear model is not a strawman — it gets the same
   data, the same number of steps, and its own tuned learning rate. */
'use strict';
const path = require('path');
const fs = require('fs');
const { DraftModel, DRAFT_HP } = require(path.join(__dirname, '..', 'assets/js/lessons/draft-train.js'));

const STEPS = parseInt(process.env.STEPS || '60000', 10);

function train(kind, lr) {
  const hp = Object.assign({}, DRAFT_HP, lr ? { lr } : null);
  const m = new DraftModel({ kind, hp, seed: 5 });
  let best = Infinity, bestNet = null, bestAt = 0, bestEval = null;
  for (let s = 1; s <= STEPS; s++) {
    m.trainBatch();
    if (s % 1000 === 0) {
      const e = m.evaluate();
      if (e.loss < best) { best = e.loss; bestNet = m.net.toJSON(); bestAt = s; bestEval = e; }
      if (s % 10000 === 0) {
        console.log(`  ${kind.padEnd(6)} step ${String(s).padStart(6)}  test ${e.loss.toFixed(4)}` +
                    `  acc ${(e.accuracy * 100).toFixed(1)}%  corr ${e.correlation.toFixed(3)}`);
      }
    }
  }
  const final = m.evaluate();
  console.log(`  ${kind}: best test ${best.toFixed(4)} at step ${bestAt}, final ${final.loss.toFixed(4)}`);
  // Ship the best held-out checkpoint, which is the one a careful person keeps.
  m.net = require(path.join(__dirname, '..', 'assets/js/lib/nn.js')).MLP.fromJSON(bestNet);
  const inter = m.interactions();
  return { kind, net: bestNet, step: bestAt, eval: bestEval, inter, lr: hp.lr };
}

console.log(`training on ${DRAFT_HP.trainMatches} matches, ${STEPS} steps each`);
const deep = train('deep');
const linear = train('linear', 0.02);   // a linear model tolerates, and wants, a larger step

const out = {
  rosterSeed: 99,
  seed: 5,
  hp: DRAFT_HP,
  models: [deep, linear].map((m) => ({
    kind: m.kind, net: m.net, step: m.step, lr: m.lr,
    loss: +m.eval.loss.toFixed(4),
    accuracy: +m.eval.accuracy.toFixed(4),
    correlation: +m.eval.correlation.toFixed(4),
    baseline: +m.eval.baseline.toFixed(4),
    inter: {
      strong: +m.inter.strong.toFixed(4),
      plain: +m.inter.plain.toFixed(4),
      pairs: m.inter.pairs,
      compared: m.inter.compared,
      correlation: +m.inter.correlation.toFixed(4),
      top: m.inter.top.map((t) => ({ i: t.i, j: t.j, model: +t.model.toFixed(3),
                                     truth: +t.truth.toFixed(3), real: t.real })),
    },
  })),
};

const dest = path.join(__dirname, '..', 'assets/models/draft-models.js');
/* Written so the page can load it with a plain script tag and the test suite
   can require it, which is what lets the tests check that these weights really
   do score what the page says they score. */
fs.writeFileSync(dest,
  '/* Generated by tools/train-draft.cjs. Two models trained on the same match\n' +
  '   results from the same roster, kept at their best held-out checkpoint. */\n' +
  ';(function (root) {\n' +
  '  var data = ' + JSON.stringify(out) + ';\n' +
  '  if (typeof module === \'object\' && module.exports) module.exports = data;\n' +
  '  else root.ML_DRAFT = data;\n' +
  '})(typeof self !== \'undefined\' ? self : this);\n');
console.log(`\nwrote ${dest} (${(fs.statSync(dest).size / 1024).toFixed(0)} KB)`);
for (const m of out.models) {
  console.log(`  ${m.kind.padEnd(6)} loss ${m.loss}  acc ${(m.accuracy * 100).toFixed(1)}%  corr ${m.correlation}` +
              `  interaction ${m.inter.strong.toFixed(3)} vs ${m.inter.plain.toFixed(3)}` +
              `  (corr with truth ${m.inter.correlation.toFixed(3)})`);
}
